"""Add pin_hash and voice_research_data

Revision ID: fdbb94fbb203
Revises: 8eb44ba281de
Create Date: 2026-06-24 13:34:12.740238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdbb94fbb203'
down_revision: Union[str, Sequence[str], None] = '8eb44ba281de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('pin_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'pin_hash')
    # ### end Alembic commands ###
